--+ Payment Register
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct C_XX_SV_PAY_REGISTER.ldt PROGRAM APPLICATION_SHORT_NAME="XBOL" CONCURRENT_PROGRAM_NAME="XX_SV_PAY_REGISTER"

Request Groups:
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afcpreqg.lct R_All_Reports.ldt REQUEST_GROUP REQUEST_GROUP_NAME="All Reports" APPLICATION_SHORT_NAME="SQLAP"

XML

FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $XDO_TOP/patch/115/import/xdotmpl.lct D_XX_SV_PAY_REGISTER.ldt XDO_DS_DEFINITIONS APPLICATION_SHORT_NAME="XBOL" DATA_SOURCE_CODE="XX_SV_PAY_REGISTER"


--+ Load Bank Accounts

Concurrentes:

FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct C_XX_SV_AP_LOAD_EXT_BANK_ACC.ldt PROGRAM APPLICATION_SHORT_NAME="XBOL" CONCURRENT_PROGRAM_NAME="XX_SV_AP_LOAD_EXT_BANK_ACC"
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct C_XXAP_SUPPLIER_BANK_ACC_SITE.ldt PROGRAM APPLICATION_SHORT_NAME="XBOL" CONCURRENT_PROGRAM_NAME="XXAP_SUPPLIER_BANK_ACC_SITE"
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct C_XXSVPURGTEMPEXTBANKACCTS.ldt PROGRAM APPLICATION_SHORT_NAME="XBOL" CONCURRENT_PROGRAM_NAME="XXSVPURGTEMPEXTBANKACCTS"



Request Groups:
FNDLOAD apps/A7bPH2qh O Y DOWNLOAD $FND_TOP/patch/115/import/afcpreqg.lct All_Reports_AP_SV.ldt REQUEST_GROUP REQUEST_GROUP_NAME="All Reports" APPLICATION_SHORT_NAME="SQLAP"

--+ Supplier Sites

FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afcpreqg.lct All_Reports_AP_SV.ldt REQUEST_GROUP REQUEST_GROUP_NAME="All Reports" APPLICATION_SHORT_NAME="SQLAP"

FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct C_XX_SV_AP_TEMP_SUPPLIER_SITES.ldt PROGRAM APPLICATION_SHORT_NAME="XBOL" CONCURRENT_PROGRAM_NAME="XX_SV_AP_UPLOADSUPSITES"

FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct C_XX_SV_AP_UPDATE_SUPPLIER_SITES.ldt PROGRAM APPLICATION_SHORT_NAME="XBOL" CONCURRENT_PROGRAM_NAME="XX_SV_AP_UPDATE_SUPPLIER_SITES"

FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct C_XX_SV_AP_PURGESUPSITES.ldt PROGRAM APPLICATION_SHORT_NAME="XBOL" CONCURRENT_PROGRAM_NAME="XX_SV_AP_PURGESUPSITES"

--+  Banking Details


ValueSet
FNDLOAD apps/A7bPH2qh O Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct V_XX_SV_PAYMENT_DELIVERY_METHOD.ldt VALUE_SET FLEX_VALUE_SET_NAME="XX_SV_PAYMENT_DELIVERY_METHOD"

FlexField
-- Supplier Sites
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct F_PO_VENDOR_SITES_SV.ldt DESC_FLEX APPLICATION_SHORT_NAME="PO" DESCRIPTIVE_FLEXFIELD_NAME="PO_VENDOR_SITES" 
-- Formato del Archivo
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct F_CE_PAYMENT_DOCUMENTS_SV.ldt DESC_FLEX APPLICATION_SHORT_NAME="CE" DESCRIPTIVE_FLEXFIELD_NAME="CE_PAYMENT_DOCUMENTS" 
-- Check Status 
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct F_AP_CHECKS.ldt DESC_FLEX APPLICATION_SHORT_NAME="SQLAP" DESCRIPTIVE_FLEXFIELD_NAME="AP_CHECKS" 

-- + Pago electronico
Concurrente
--Archivo
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct C_XX_SV_FLEX_BANK_FILE.ldt PROGRAM APPLICATION_SHORT_NAME="XBOL" CONCURRENT_PROGRAM_NAME="XX_SV_FLEX_BANK_FILE"
--Actualizar el estado
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct C_XXSVUPDATECHECKSTATUS.ldt PROGRAM APPLICATION_SHORT_NAME="XBOL" CONCURRENT_PROGRAM_NAME="XXSVUPDATECHECKSTATUS"

-- Request Group
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afcpreqg.lct R_All_Reports.ldt REQUEST_GROUP REQUEST_GROUP_NAME="All Reports" APPLICATION_SHORT_NAME="SQLAP"

--Value set de usuarios con permisos
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct V_XXSVAPSETUPSTATUSCHECK.ldt VALUE_SET FLEX_VALUE_SET_NAME="XXSVAPSETUPSTATUSCHECK"


Descarga de LDT de UAT o DEV

Concurrentes:
FNDLOAD apps/Y7bQH9lb O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct C_XX_SV_FLEX_BANK_FILE.ldt PROGRAM APPLICATION_SHORT_NAME="XBOL" CONCURRENT_PROGRAM_NAME="XX_SV_FLEX_BANK_FILE"

ValueSet
FNDLOAD apps/A7bPH2qh O Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct V_XXSVLISTBANK.ldt VALUE_SET FLEX_VALUE_SET_NAME="XXSVLISTBANK"
FNDLOAD apps/A7bPH2qh O Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct V_XXSVLISTBAACCOUNTS.ldt VALUE_SET FLEX_VALUE_SET_NAME="XXSVLISTBAACCOUNTS"
FNDLOAD apps/A7bPH2qh O Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct V_XXSVLISTDOCSEQEFTPAY.ldt VALUE_SET FLEX_VALUE_SET_NAME="XXSVLISTDOCSEQEFTPAY"
FNDLOAD apps/A7bPH2qh O Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct V_XXSVEPAYFORMATFILE.ldt VALUE_SET FLEX_VALUE_SET_NAME="XXSVEPAYFORMATFILE"

FlexField
FNDLOAD apps/A7bPH2qh O Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct FLEX_FIELD_FORMAT_FILE_SV.ldt DESC_FLEX APPLICATION_SHORT_NAME="CE" DESCRIPTIVE_FLEXFIELD_NAME="CE_PAYMENT_DOCUMENTS" 
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct F_AP_CHECKS.ldt DESC_FLEX APPLICATION_SHORT_NAME="SQLAP" DESCRIPTIVE_FLEXFIELD_NAME="AP_CHECKS" 

--CRP --FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct F_TRANSACTION_CODE.ldt DESC_FLEX APPLICATION_SHORT_NAME="PO" DESCRIPTIVE_FLEXFIELD_NAME="PO_VENDOR_SITES"
FNDLOAD apps/Y7bQH9lb O Y DOWNLOAD $FND_TOP/patch/115/import/afffload.lct F_PO_VENDOR_SITES.ldt DESC_FLEX APPLICATION_SHORT_NAME="PO" DESCRIPTIVE_FLEXFIELD_NAME="PO_VENDOR_SITES"

Request Group
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afcpreqg.lct Re_All_Reports.ldt REQUEST_GROUP REQUEST_GROUP_NAME="All Reports" APPLICATION_SHORT_NAME="SQLAP"
Y7bQH9lb
Menu:
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afsload.lct AP_NAVIGATE_GUI12_MN.ldt MENU MENU_NAME="AP_NAVIGATE_GUI12"



##------------- Forms ------------------
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afsload.lct XX_AP_EPAYMENTS_FRM.ldt FORM FORM_NAME="XX_AP_EPAYMENTS"

## ------------- Forms Function ------------------
FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afsload.lct XX_AP_EPAYMENTS_FUNC.ldt FUNCTION FUNCTION_NAME="XX_AP_EPAYMENTS"

---------------MENU--------------

FNDLOAD apps/cdqcejfwz9 O Y DOWNLOAD $FND_TOP/patch/115/import/afsload.lct XX_AP_EPAYMENTS/AP_NAVIGATE_GUI12_MN.ldt MENU MENU_NAME=AP_NAVIGATE_GUI12



FNDLOAD apps/cdqcejfwz9 0 Y DOWNLOAD $FND_TOP/patch/115/import/affrmcus.lct /tmp/FP_XXCSI.ldt \
  FND_FORM_CUSTOM_RULES FUNCTION_NAME="%"

