SELECT * FROM XDO_DS_DEFINITIONS_TL
  WHERE APPLICATION_SHORT_NAME = 'XBOL'
  AND DATA_SOURCE_CODE LIKE '%XXSVCIPACTFI%';
 
SELECT * FROM XDO_DS_DEFINITIONS_B
  WHERE APPLICATION_SHORT_NAME = 'XBOL'
  AND DATA_SOURCE_CODE LIKE '%XXSVCIPACTFI%';  
 
SELECT * FROM XDO_TEMPLATES_TL
  WHERE APPLICATION_SHORT_NAME = 'XBOL'
  AND TEMPLATE_CODE LIKE '%XXSVCIPACTFI%';
 
SELECT * FROM XDO_TEMPLATES_B
  WHERE APPLICATION_SHORT_NAME = 'XBOL'
  AND TEMPLATE_CODE LIKE '%XXSVCIPACTFI%';
  

SELECT * FROM XDO.XDO_LOBS WHERE LOB_CODE LIKE '%XXSVCIPACTFI%';

/*        Borrar el XML y el RTF   */

BEGIN
DELETE FROM XDO_DS_DEFINITIONS_TL
  WHERE APPLICATION_SHORT_NAME = 'XBOL'
  AND DATA_SOURCE_CODE LIKE '%XXSVCIPACTFI%';
COMMIT;
  DELETE FROM XDO_DS_DEFINITIONS_B
  WHERE APPLICATION_SHORT_NAME = 'XBOL'
  AND DATA_SOURCE_CODE LIKE '%XXSVCIPACTFI%';
COMMIT;
DELETE FROM XDO_TEMPLATES_TL
  WHERE APPLICATION_SHORT_NAME = 'XBOL'
  AND TEMPLATE_CODE LIKE '%XXSVCIPACTFI%';
 
  DELETE FROM XDO_TEMPLATES_B
  WHERE APPLICATION_SHORT_NAME = 'XBOL'
  AND TEMPLATE_CODE LIKE '%XXSVCIPACTFI%';
COMMIT;
delete FROM XDO.XDO_LOBS WHERE LOB_CODE LIKE '%XXSVCIPACTFI%';
COMMIT;
END;

begin
     XDO_DS_DEFINITIONS_PKG.DELETE_ROW (X_APPLICATION_SHORT_NAME => 'XBOL',  X_DATA_SOURCE_CODE =>'XXSVCIPACTFI');
    XDO_TEMPLATES_PKG.DELETE_ROW (X_APPLICATION_SHORT_NAME => 'XBOL',  X_TEMPLATE_CODE =>'XXSVCIPACTFI');
    DELETE FROM XDO.XDO_LOBS WHERE LOB_CODE = 'XXSVCIPACTFI';
    COMMIT;
end;
